// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NettyMulProtobuf.proto

package com.chenws.netty.protobuf.proto;

public final class NettyMulProtobuf {
  private NettyMulProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MultipleMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MultipleMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.MultipleMessage.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    int getDataTypeValue();
    /**
     * <code>.MultipleMessage.DataType data_type = 1;</code>
     * @return The dataType.
     */
    com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.DataType getDataType();

    /**
     * <code>.Student student = 2;</code>
     * @return Whether the student field is set.
     */
    boolean hasStudent();
    /**
     * <code>.Student student = 2;</code>
     * @return The student.
     */
    com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student getStudent();
    /**
     * <code>.Student student = 2;</code>
     */
    com.chenws.netty.protobuf.proto.NettyMulProtobuf.StudentOrBuilder getStudentOrBuilder();

    /**
     * <code>.School school = 3;</code>
     * @return Whether the school field is set.
     */
    boolean hasSchool();
    /**
     * <code>.School school = 3;</code>
     * @return The school.
     */
    com.chenws.netty.protobuf.proto.NettyMulProtobuf.School getSchool();
    /**
     * <code>.School school = 3;</code>
     */
    com.chenws.netty.protobuf.proto.NettyMulProtobuf.SchoolOrBuilder getSchoolOrBuilder();

    public com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code MultipleMessage}
   */
  public  static final class MultipleMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MultipleMessage)
      MultipleMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MultipleMessage.newBuilder() to construct.
    private MultipleMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultipleMessage() {
      dataType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MultipleMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultipleMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((com.chenws.netty.protobuf.proto.NettyMulProtobuf.School) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.chenws.netty.protobuf.proto.NettyMulProtobuf.School) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chenws.netty.protobuf.proto.NettyMulProtobuf.internal_static_MultipleMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chenws.netty.protobuf.proto.NettyMulProtobuf.internal_static_MultipleMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.class, com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code MultipleMessage.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>StudentType = 0;</code>
       */
      StudentType(0),
      /**
       * <code>SchoolType = 1;</code>
       */
      SchoolType(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>StudentType = 0;</code>
       */
      public static final int StudentType_VALUE = 0;
      /**
       * <code>SchoolType = 1;</code>
       */
      public static final int SchoolType_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return StudentType;
          case 1: return SchoolType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MultipleMessage.DataType)
    }

    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      STUDENT(2),
      SCHOOL(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return STUDENT;
          case 3: return SCHOOL;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>.MultipleMessage.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.MultipleMessage.DataType data_type = 1;</code>
     * @return The dataType.
     */
    public com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.DataType result = com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.DataType.valueOf(dataType_);
      return result == null ? com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.DataType.UNRECOGNIZED : result;
    }

    public static final int STUDENT_FIELD_NUMBER = 2;
    /**
     * <code>.Student student = 2;</code>
     * @return Whether the student field is set.
     */
    public boolean hasStudent() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.Student student = 2;</code>
     * @return The student.
     */
    public com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student getStudent() {
      if (dataBodyCase_ == 2) {
         return (com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student) dataBody_;
      }
      return com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.getDefaultInstance();
    }
    /**
     * <code>.Student student = 2;</code>
     */
    public com.chenws.netty.protobuf.proto.NettyMulProtobuf.StudentOrBuilder getStudentOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student) dataBody_;
      }
      return com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.getDefaultInstance();
    }

    public static final int SCHOOL_FIELD_NUMBER = 3;
    /**
     * <code>.School school = 3;</code>
     * @return Whether the school field is set.
     */
    public boolean hasSchool() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.School school = 3;</code>
     * @return The school.
     */
    public com.chenws.netty.protobuf.proto.NettyMulProtobuf.School getSchool() {
      if (dataBodyCase_ == 3) {
         return (com.chenws.netty.protobuf.proto.NettyMulProtobuf.School) dataBody_;
      }
      return com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.getDefaultInstance();
    }
    /**
     * <code>.School school = 3;</code>
     */
    public com.chenws.netty.protobuf.proto.NettyMulProtobuf.SchoolOrBuilder getSchoolOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (com.chenws.netty.protobuf.proto.NettyMulProtobuf.School) dataBody_;
      }
      return com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.DataType.StudentType.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (com.chenws.netty.protobuf.proto.NettyMulProtobuf.School) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.DataType.StudentType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.chenws.netty.protobuf.proto.NettyMulProtobuf.School) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage)) {
        return super.equals(obj);
      }
      com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage other = (com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage) obj;

      if (dataType_ != other.dataType_) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getStudent()
              .equals(other.getStudent())) return false;
          break;
        case 3:
          if (!getSchool()
              .equals(other.getSchool())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + STUDENT_FIELD_NUMBER;
          hash = (53 * hash) + getStudent().hashCode();
          break;
        case 3:
          hash = (37 * hash) + SCHOOL_FIELD_NUMBER;
          hash = (53 * hash) + getSchool().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MultipleMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MultipleMessage)
        com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chenws.netty.protobuf.proto.NettyMulProtobuf.internal_static_MultipleMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chenws.netty.protobuf.proto.NettyMulProtobuf.internal_static_MultipleMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.class, com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.Builder.class);
      }

      // Construct using com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chenws.netty.protobuf.proto.NettyMulProtobuf.internal_static_MultipleMessage_descriptor;
      }

      @java.lang.Override
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage getDefaultInstanceForType() {
        return com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage build() {
        com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage buildPartial() {
        com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage result = new com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage(this);
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (studentBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = studentBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (schoolBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = schoolBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage) {
          return mergeFrom((com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage other) {
        if (other == com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case STUDENT: {
            mergeStudent(other.getStudent());
            break;
          }
          case SCHOOL: {
            mergeSchool(other.getSchool());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int dataType_ = 0;
      /**
       * <code>.MultipleMessage.DataType data_type = 1;</code>
       * @return The enum numeric value on the wire for dataType.
       */
      public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <code>.MultipleMessage.DataType data_type = 1;</code>
       * @param value The enum numeric value on the wire for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MultipleMessage.DataType data_type = 1;</code>
       * @return The dataType.
       */
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.DataType getDataType() {
        @SuppressWarnings("deprecation")
        com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.DataType result = com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.DataType.valueOf(dataType_);
        return result == null ? com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.MultipleMessage.DataType data_type = 1;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MultipleMessage.DataType data_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student, com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.Builder, com.chenws.netty.protobuf.proto.NettyMulProtobuf.StudentOrBuilder> studentBuilder_;
      /**
       * <code>.Student student = 2;</code>
       * @return Whether the student field is set.
       */
      public boolean hasStudent() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.Student student = 2;</code>
       * @return The student.
       */
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student getStudent() {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student) dataBody_;
          }
          return com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return studentBuilder_.getMessage();
          }
          return com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.getDefaultInstance();
        }
      }
      /**
       * <code>.Student student = 2;</code>
       */
      public Builder setStudent(com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          studentBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Student student = 2;</code>
       */
      public Builder setStudent(
          com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          studentBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Student student = 2;</code>
       */
      public Builder mergeStudent(com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student value) {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.getDefaultInstance()) {
            dataBody_ = com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.newBuilder((com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            studentBuilder_.mergeFrom(value);
          }
          studentBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Student student = 2;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          studentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Student student = 2;</code>
       */
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.Builder getStudentBuilder() {
        return getStudentFieldBuilder().getBuilder();
      }
      /**
       * <code>.Student student = 2;</code>
       */
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.StudentOrBuilder getStudentOrBuilder() {
        if ((dataBodyCase_ == 2) && (studentBuilder_ != null)) {
          return studentBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student) dataBody_;
          }
          return com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.getDefaultInstance();
        }
      }
      /**
       * <code>.Student student = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student, com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.Builder, com.chenws.netty.protobuf.proto.NettyMulProtobuf.StudentOrBuilder> 
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.getDefaultInstance();
          }
          studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student, com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.Builder, com.chenws.netty.protobuf.proto.NettyMulProtobuf.StudentOrBuilder>(
                  (com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return studentBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.chenws.netty.protobuf.proto.NettyMulProtobuf.School, com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.Builder, com.chenws.netty.protobuf.proto.NettyMulProtobuf.SchoolOrBuilder> schoolBuilder_;
      /**
       * <code>.School school = 3;</code>
       * @return Whether the school field is set.
       */
      public boolean hasSchool() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.School school = 3;</code>
       * @return The school.
       */
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.School getSchool() {
        if (schoolBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (com.chenws.netty.protobuf.proto.NettyMulProtobuf.School) dataBody_;
          }
          return com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return schoolBuilder_.getMessage();
          }
          return com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.getDefaultInstance();
        }
      }
      /**
       * <code>.School school = 3;</code>
       */
      public Builder setSchool(com.chenws.netty.protobuf.proto.NettyMulProtobuf.School value) {
        if (schoolBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          schoolBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.School school = 3;</code>
       */
      public Builder setSchool(
          com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.Builder builderForValue) {
        if (schoolBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          schoolBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.School school = 3;</code>
       */
      public Builder mergeSchool(com.chenws.netty.protobuf.proto.NettyMulProtobuf.School value) {
        if (schoolBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.getDefaultInstance()) {
            dataBody_ = com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.newBuilder((com.chenws.netty.protobuf.proto.NettyMulProtobuf.School) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            schoolBuilder_.mergeFrom(value);
          }
          schoolBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.School school = 3;</code>
       */
      public Builder clearSchool() {
        if (schoolBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          schoolBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.School school = 3;</code>
       */
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.Builder getSchoolBuilder() {
        return getSchoolFieldBuilder().getBuilder();
      }
      /**
       * <code>.School school = 3;</code>
       */
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.SchoolOrBuilder getSchoolOrBuilder() {
        if ((dataBodyCase_ == 3) && (schoolBuilder_ != null)) {
          return schoolBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (com.chenws.netty.protobuf.proto.NettyMulProtobuf.School) dataBody_;
          }
          return com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.getDefaultInstance();
        }
      }
      /**
       * <code>.School school = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.chenws.netty.protobuf.proto.NettyMulProtobuf.School, com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.Builder, com.chenws.netty.protobuf.proto.NettyMulProtobuf.SchoolOrBuilder> 
          getSchoolFieldBuilder() {
        if (schoolBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.getDefaultInstance();
          }
          schoolBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.chenws.netty.protobuf.proto.NettyMulProtobuf.School, com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.Builder, com.chenws.netty.protobuf.proto.NettyMulProtobuf.SchoolOrBuilder>(
                  (com.chenws.netty.protobuf.proto.NettyMulProtobuf.School) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return schoolBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MultipleMessage)
    }

    // @@protoc_insertion_point(class_scope:MultipleMessage)
    private static final com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage();
    }

    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultipleMessage>
        PARSER = new com.google.protobuf.AbstractParser<MultipleMessage>() {
      @java.lang.Override
      public MultipleMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultipleMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultipleMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultipleMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chenws.netty.protobuf.proto.NettyMulProtobuf.MultipleMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>string address = 3;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 3;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      address_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chenws.netty.protobuf.proto.NettyMulProtobuf.internal_static_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chenws.netty.protobuf.proto.NettyMulProtobuf.internal_static_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.class, com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    public int getAge() {
      return age_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 3;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 3;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student)) {
        return super.equals(obj);
      }
      com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student other = (com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Student)
        com.chenws.netty.protobuf.proto.NettyMulProtobuf.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chenws.netty.protobuf.proto.NettyMulProtobuf.internal_static_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chenws.netty.protobuf.proto.NettyMulProtobuf.internal_static_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.class, com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.Builder.class);
      }

      // Construct using com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        address_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chenws.netty.protobuf.proto.NettyMulProtobuf.internal_static_Student_descriptor;
      }

      @java.lang.Override
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student getDefaultInstanceForType() {
        return com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.getDefaultInstance();
      }

      @java.lang.Override
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student build() {
        com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student buildPartial() {
        com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student result = new com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student(this);
        result.name_ = name_;
        result.age_ = age_;
        result.address_ = address_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student) {
          return mergeFrom((com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student other) {
        if (other == com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 3;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 3;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 3;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 3;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Student)
    }

    // @@protoc_insertion_point(class_scope:Student)
    private static final com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student();
    }

    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chenws.netty.protobuf.proto.NettyMulProtobuf.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SchoolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:School)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string school_name = 1;</code>
     * @return The schoolName.
     */
    java.lang.String getSchoolName();
    /**
     * <code>string school_name = 1;</code>
     * @return The bytes for schoolName.
     */
    com.google.protobuf.ByteString
        getSchoolNameBytes();

    /**
     * <code>string school_address = 2;</code>
     * @return The schoolAddress.
     */
    java.lang.String getSchoolAddress();
    /**
     * <code>string school_address = 2;</code>
     * @return The bytes for schoolAddress.
     */
    com.google.protobuf.ByteString
        getSchoolAddressBytes();
  }
  /**
   * Protobuf type {@code School}
   */
  public  static final class School extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:School)
      SchoolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use School.newBuilder() to construct.
    private School(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private School() {
      schoolName_ = "";
      schoolAddress_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new School();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private School(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              schoolName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              schoolAddress_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chenws.netty.protobuf.proto.NettyMulProtobuf.internal_static_School_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chenws.netty.protobuf.proto.NettyMulProtobuf.internal_static_School_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.class, com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.Builder.class);
    }

    public static final int SCHOOL_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object schoolName_;
    /**
     * <code>string school_name = 1;</code>
     * @return The schoolName.
     */
    public java.lang.String getSchoolName() {
      java.lang.Object ref = schoolName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schoolName_ = s;
        return s;
      }
    }
    /**
     * <code>string school_name = 1;</code>
     * @return The bytes for schoolName.
     */
    public com.google.protobuf.ByteString
        getSchoolNameBytes() {
      java.lang.Object ref = schoolName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schoolName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCHOOL_ADDRESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object schoolAddress_;
    /**
     * <code>string school_address = 2;</code>
     * @return The schoolAddress.
     */
    public java.lang.String getSchoolAddress() {
      java.lang.Object ref = schoolAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schoolAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string school_address = 2;</code>
     * @return The bytes for schoolAddress.
     */
    public com.google.protobuf.ByteString
        getSchoolAddressBytes() {
      java.lang.Object ref = schoolAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schoolAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSchoolNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, schoolName_);
      }
      if (!getSchoolAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, schoolAddress_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSchoolNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, schoolName_);
      }
      if (!getSchoolAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, schoolAddress_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chenws.netty.protobuf.proto.NettyMulProtobuf.School)) {
        return super.equals(obj);
      }
      com.chenws.netty.protobuf.proto.NettyMulProtobuf.School other = (com.chenws.netty.protobuf.proto.NettyMulProtobuf.School) obj;

      if (!getSchoolName()
          .equals(other.getSchoolName())) return false;
      if (!getSchoolAddress()
          .equals(other.getSchoolAddress())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCHOOL_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSchoolName().hashCode();
      hash = (37 * hash) + SCHOOL_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getSchoolAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.School parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.School parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.School parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.School parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.School parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.School parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.School parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.School parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.School parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.School parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.School parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.School parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chenws.netty.protobuf.proto.NettyMulProtobuf.School prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code School}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:School)
        com.chenws.netty.protobuf.proto.NettyMulProtobuf.SchoolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chenws.netty.protobuf.proto.NettyMulProtobuf.internal_static_School_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chenws.netty.protobuf.proto.NettyMulProtobuf.internal_static_School_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.class, com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.Builder.class);
      }

      // Construct using com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        schoolName_ = "";

        schoolAddress_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chenws.netty.protobuf.proto.NettyMulProtobuf.internal_static_School_descriptor;
      }

      @java.lang.Override
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.School getDefaultInstanceForType() {
        return com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.getDefaultInstance();
      }

      @java.lang.Override
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.School build() {
        com.chenws.netty.protobuf.proto.NettyMulProtobuf.School result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chenws.netty.protobuf.proto.NettyMulProtobuf.School buildPartial() {
        com.chenws.netty.protobuf.proto.NettyMulProtobuf.School result = new com.chenws.netty.protobuf.proto.NettyMulProtobuf.School(this);
        result.schoolName_ = schoolName_;
        result.schoolAddress_ = schoolAddress_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chenws.netty.protobuf.proto.NettyMulProtobuf.School) {
          return mergeFrom((com.chenws.netty.protobuf.proto.NettyMulProtobuf.School)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chenws.netty.protobuf.proto.NettyMulProtobuf.School other) {
        if (other == com.chenws.netty.protobuf.proto.NettyMulProtobuf.School.getDefaultInstance()) return this;
        if (!other.getSchoolName().isEmpty()) {
          schoolName_ = other.schoolName_;
          onChanged();
        }
        if (!other.getSchoolAddress().isEmpty()) {
          schoolAddress_ = other.schoolAddress_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chenws.netty.protobuf.proto.NettyMulProtobuf.School parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chenws.netty.protobuf.proto.NettyMulProtobuf.School) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object schoolName_ = "";
      /**
       * <code>string school_name = 1;</code>
       * @return The schoolName.
       */
      public java.lang.String getSchoolName() {
        java.lang.Object ref = schoolName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          schoolName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string school_name = 1;</code>
       * @return The bytes for schoolName.
       */
      public com.google.protobuf.ByteString
          getSchoolNameBytes() {
        java.lang.Object ref = schoolName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          schoolName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string school_name = 1;</code>
       * @param value The schoolName to set.
       * @return This builder for chaining.
       */
      public Builder setSchoolName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        schoolName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string school_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSchoolName() {
        
        schoolName_ = getDefaultInstance().getSchoolName();
        onChanged();
        return this;
      }
      /**
       * <code>string school_name = 1;</code>
       * @param value The bytes for schoolName to set.
       * @return This builder for chaining.
       */
      public Builder setSchoolNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        schoolName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object schoolAddress_ = "";
      /**
       * <code>string school_address = 2;</code>
       * @return The schoolAddress.
       */
      public java.lang.String getSchoolAddress() {
        java.lang.Object ref = schoolAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          schoolAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string school_address = 2;</code>
       * @return The bytes for schoolAddress.
       */
      public com.google.protobuf.ByteString
          getSchoolAddressBytes() {
        java.lang.Object ref = schoolAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          schoolAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string school_address = 2;</code>
       * @param value The schoolAddress to set.
       * @return This builder for chaining.
       */
      public Builder setSchoolAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        schoolAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string school_address = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSchoolAddress() {
        
        schoolAddress_ = getDefaultInstance().getSchoolAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string school_address = 2;</code>
       * @param value The bytes for schoolAddress to set.
       * @return This builder for chaining.
       */
      public Builder setSchoolAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        schoolAddress_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:School)
    }

    // @@protoc_insertion_point(class_scope:School)
    private static final com.chenws.netty.protobuf.proto.NettyMulProtobuf.School DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chenws.netty.protobuf.proto.NettyMulProtobuf.School();
    }

    public static com.chenws.netty.protobuf.proto.NettyMulProtobuf.School getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<School>
        PARSER = new com.google.protobuf.AbstractParser<School>() {
      @java.lang.Override
      public School parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new School(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<School> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<School> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chenws.netty.protobuf.proto.NettyMulProtobuf.School getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MultipleMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MultipleMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_School_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_School_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026NettyMulProtobuf.proto\"\260\001\n\017MultipleMes" +
      "sage\022,\n\tdata_type\030\001 \001(\0162\031.MultipleMessag" +
      "e.DataType\022\033\n\007student\030\002 \001(\0132\010.StudentH\000\022" +
      "\031\n\006school\030\003 \001(\0132\007.SchoolH\000\"+\n\010DataType\022\017" +
      "\n\013StudentType\020\000\022\016\n\nSchoolType\020\001B\n\n\010dataB" +
      "ody\"5\n\007Student\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(" +
      "\005\022\017\n\007address\030\003 \001(\t\"5\n\006School\022\023\n\013school_n" +
      "ame\030\001 \001(\t\022\026\n\016school_address\030\002 \001(\tB3\n\037com" +
      ".chenws.netty.protobuf.protoB\020NettyMulPr" +
      "otobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MultipleMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MultipleMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MultipleMessage_descriptor,
        new java.lang.String[] { "DataType", "Student", "School", "DataBody", });
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Student_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", });
    internal_static_School_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_School_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_School_descriptor,
        new java.lang.String[] { "SchoolName", "SchoolAddress", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
